table Dim_Date_Period
	lineageTag: a804ca8e-2fa1-4d90-a482-b1c7ff96cf32

	column DATE_DIM_ID
		dataType: int64
		formatString: 0
		lineageTag: bd573198-af50-4e2c-b941-967547d92f8d
		summarizeBy: none
		sourceColumn: DATE_DIM_ID

		annotation SummarizationSetBy = Automatic

	column DATE_PERIOD
		dataType: string
		lineageTag: 0fdd7bcf-14cf-4b72-9a66-11f5e840abd1
		summarizeBy: none
		sourceColumn: DATE_PERIOD
		sortByColumn: PERIOD_ORDER

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column PERIOD_ORDER
		dataType: int64
		formatString: 0
		lineageTag: 18ddd1ea-d2d9-4f07-9107-47849eea26ac
		summarizeBy: sum
		sourceColumn: PERIOD_ORDER

		annotation SummarizationSetBy = Automatic

	partition Dim_Date_Period = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Data_Files\Dim_Date_Period.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DATE_DIM_ID", Int64.Type}, {"DATE_PERIOD", type text}, {"PERIOD_ORDER", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

