name: Lint SQL Files

on: 
  workflow_dispatch:
  push:
    paths:
      - '**/*.sql'
  pull_request:
    paths:
      - '**/*.sql'

jobs:
  lint-sql:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install SQLFluff
        run: pip install sqlfluff==0.3.6

      - name: Lint all SQL files
        run: sqlfluff lint . --dialect snowflake
